# Generated by Django 2.2 on 2020-05-19 17:20

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_post_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='meet_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meet',
            name='participants',
            field=models.ManyToManyField(related_name='meets', to=settings.AUTH_USER_MODEL),
        ),
    ]
