# Generated by Django 2.2 on 2020-05-19 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200519_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meets', to=settings.AUTH_USER_MODEL),
        ),
    ]
