# Generated by Django 2.2 on 2020-05-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200519_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='title',
            field=models.CharField(default='QQQ', max_length=100),
            preserve_default=False,
        ),
    ]
